BLAST_RECIPES.recipeBuilder()
  .input(dust, SiliconDioxide, 50)
  .input(dust, Sapphire, 4)
  .input(dust, SodaAsh, 1)
  .output(dust, NaZSM5, 1)
  .fluidOutputs(CarbonDioxide.getFluid(300))
  .duration(1000)
  .blastFurnaceTemp(10240)
  .EUt(1572864)
  .buildAndRegister();

CHEMICAL_RECIPES.recipeBuilder()
  .fluidInputs(Nitrochlorobenzene.getFluid(1000))
  .fluidInputs(Ammonia.getFluid(2000))
  .notConsumable(Water.getFluid(2000))
  .notConsumable(dust, Copper)
  .output(dust, PPhenylenediamine, 1)
  .output(dust, AmmoniumChloride, 2)
  .duration(1000)
  .EUt(98304)
  .buildAndRegister();

CHEMICAL_RECIPES.recipeBuilder()
  .input(dust, PPhenylenediamine, 1)
  .fluidInputs(Hydrogen.getFluid(6000))
  .notConsumable(dust, Platinum)
  .output(dust, PPhenylenediamine, 1)
  .fluidOutputs(Water.getFluid(2000))
  .duration(9600)
  .EUt(24576)
  .buildAndRegister();
